// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIEmployeeFull.Models;

namespace WebAPIEmployeeFull.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220113194413_initialmigration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPIEmployeeFull.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentID");

                    b.ToTable("departmentsprop");

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            DepartmentName = "IT"
                        },
                        new
                        {
                            DepartmentID = 2,
                            DepartmentName = "HR"
                        },
                        new
                        {
                            DepartmentID = 3,
                            DepartmentName = "PayRoll"
                        },
                        new
                        {
                            DepartmentID = 4,
                            DepartmentName = "Staffing"
                        });
                });

            modelBuilder.Entity("WebAPIEmployeeFull.Models.Employee", b =>
                {
                    b.Property<int>("EmpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EmpDateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmpFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpGender")
                        .HasColumnType("int");

                    b.Property<string>("EmpLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpSalary")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpID");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employeeprop");

                    b.HasData(
                        new
                        {
                            EmpID = 101,
                            DepartmentId = 1,
                            Email = "sara@gmail.com",
                            EmpDateofBirth = new DateTime(2000, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmpFirstName = "Sara",
                            EmpGender = 1,
                            EmpLastName = "Tondon",
                            EmpSalary = 0,
                            PhotoPath = "~/Wwwroot/Images/Flower1.jpg"
                        },
                        new
                        {
                            EmpID = 102,
                            DepartmentId = 2,
                            Email = "John@gmail.com",
                            EmpDateofBirth = new DateTime(2001, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmpFirstName = "John",
                            EmpGender = 0,
                            EmpLastName = "Srikant",
                            EmpSalary = 0,
                            PhotoPath = "~/Wwwroot/Images/Flower2.jpg"
                        });
                });

            modelBuilder.Entity("WebAPIEmployeeFull.Models.Employee", b =>
                {
                    b.HasOne("WebAPIEmployeeFull.Models.Department", "EmpdepartmentID")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmpdepartmentID");
                });
#pragma warning restore 612, 618
        }
    }
}
